/**
 * IDX Property resource: Standard Name list (all property fields per IDX schema).
 * Used in $select to request full IDX property data. ListingKey is added by the fetch.
 */
export const IDX_PROPERTY_FIELDS = [
  "AccessToProperty", "AccessibilityFeatures", "AdditionalMonthlyFee", "AdditionalMonthlyFeeFrequency",
  "AlternativePower", "Amps", "ApartmentNumber", "ApproximateAge", "ArchitecturalStyle", "AssessmentYear",
  "AssociationAmenities", "AssociationFee", "AssociationFeeIncludes", "AssociationName", "AttachedGarageYN",
  "BalconyType", "Basement", "BasementYN", "BathroomsTotalInteger", "BaySizeLengthFeet", "BaySizeLengthInches",
  "BaySizeWidthFeet", "BaySizeWidthInches", "BedroomsAboveGrade", "BedroomsBelowGrade", "BedroomsTotal",
  "BoardPropertyType", "BuildingAreaTotal", "BuildingAreaUnits", "BuildingName", "BusinessName", "BusinessType",
  "CableYNA", "CentralVacuumYN", "ChannelName", "ChattelsYN", "City", "CityRegion", "ClearHeightFeet", "ClearHeightInches",
  "CoListOfficeKey", "CoListOfficeKey3", "CoListOfficeKey4", "CoListOfficeName", "CoListOfficeName3", "CoListOfficeName4",
  "CommercialCondoFee", "CommercialCondoFeeFrequency", "CommonAreaUpcharge", "CommunityFeatures", "CondoCorpNumber",
  "ConstructionMaterials", "ContractStatus", "Cooling", "CoolingYN", "Country", "CountyOrParish", "CoveredSpaces",
  "CraneYN", "CrossStreet", "DDFYN", "DenFamilyroomYN", "DevelopmentChargesPaid", "DirectionFaces", "Directions",
  "Disclosures", "DockingType", "DoubleManShippingDoors", "DoubleManShippingDoorsHeightFeet", "DoubleManShippingDoorsHeightInches",
  "DoubleManShippingDoorsWidthFeet", "DoubleManShippingDoorsWidthInches", "DriveInLevelShippingDoors",
  "DriveInLevelShippingDoorsHeightFeet", "DriveInLevelShippingDoorsHeightInches", "DriveInLevelShippingDoorsWidthFeet",
  "DriveInLevelShippingDoorsWidthInches", "ElectricExpense", "ElectricOnPropertyYN", "ElectricYNA", "ElevatorType",
  "ElevatorYN", "EnsuiteLaundryYN", "EstimatedInventoryValueAtCost", "Expenses", "ExpirationDate", "Exposure",
  "ExteriorFeatures", "FarmFeatures", "FarmType", "FinancialStatementAvailableYN", "FireplaceFeatures", "FireplaceYN",
  "FoundationDetails", "FranchiseYN", "FreestandingYN", "FrontageLength", "Furnished", "GarageParkingSpaces",
  "GarageType", "GarageYN", "GradeLevelShippingDoors", "GradeLevelShippingDoorsHeightFeet", "GradeLevelShippingDoorsHeightInches",
  "GradeLevelShippingDoorsWidthFeet", "GradeLevelShippingDoorsWidthInches", "HSTApplication", "HeatSource", "HeatSourceMulti",
  "HeatType", "HeatTypeMulti", "HeatingExpenses", "HeatingYN", "HoursDaysOfOperation", "HoursDaysOfOperationDescription",
  "IndustrialArea", "IndustrialAreaCode", "InsuranceExpense", "InteriorFeatures",
  "InternetAddressDisplayYN", "InternetEntireListingDisplayYN", "IslandYN", "KitchensAboveGrade", "KitchensBelowGrade",
  "KitchensTotal", "LaundryFeatures", "LeaseToOwnEquipment", "LeasedLandFee", "LeasedTerms", "LegalStories",
  "LinkProperty", "LinkYN", "ListAOR", "ListOfficeKey", "ListOfficeName", "ListPrice", "ListPriceUnit",
  "LivingAreaRange", "LocalImprovements", "LocalImprovementsComments", "Locker", "LockerLevel", "LockerNumber", "LockerUnit",
  "LotDepth", "LotDimensionsSource", "LotFeatures", "LotIrregularities", "LotShape", "LotSizeArea", "LotSizeAreaUnits",
  "LotSizeRangeAcres", "LotSizeSource", "LotSizeUnits", "LotType", "LotWidth", "MaximumRentalMonthsTerm",
  "MediaChangeTimestamp", "MediaListingKey", "MinimumRentalTermMonths", "MlsStatus", "ModificationTimestamp",
  "NetOperatingIncome", "NewConstructionYN", "NumberOfFullTimeEmployees", "NumberOfKitchens", "OccupantType",
  "OfficeApartmentArea", "OfficeApartmentAreaUnit", "OriginalEntryTimestamp", "OriginatingSystemID", "OtherExpense",
  "OtherStructures", "OutOfAreaMunicipality", "OutsideStorageYN", "ParcelNumber", "ParcelNumber2", "ParcelOfTiedLand",
  "ParkingFeatures", "ParkingLevelUnit1", "ParkingLevelUnit2", "ParkingMonthlyCost", "ParkingSpaces", "ParkingSpot1",
  "ParkingSpot2", "ParkingTotal", "PercentBuilding", "PetsAllowed", "PhotosChangeTimestamp", "PoolFeatures",
  "PossessionDetails", "PossessionType", "PostalCode", "ProfessionalManagementExpense", "PropertyAttachedYN",
  "PropertyFeatures", "PropertyManagementCompany", "PropertySubType", "PropertyType", "PropertyUse", "PublicRemarks",
  "PublicRemarksExtras", "Rail", "RentIncludes", "RetailArea", "RetailAreaCode", "RoadAccessFee", "RollNumber", "Roof",
  "RoomHeight", "RoomType", "RoomsAboveGrade", "RoomsBelowGrade", "RoomsTotal", "RuralUtilities", "SeasonalDwelling",
  "SeatingCapacity", "SecurityFeatures", "SeniorCommunityYN", "Sewer", "Shoreline", "ShorelineAllowance", "ShorelineExposureMulti",
  "ShowingRequirements", "SignOnPropertyYN", "SoilTest", "SoilType", "SpaYN", "SpecialDesignation", "SquareFootSource",
  "StandardStatus", "StateOrProvince", "StreetDirPrefix", "StreetDirSuffix", "StreetName", "StreetNumber", "StreetSuffix",
  "StructureType", "SurveyAvailableYN", "SurveyType", "SystemModificationTimestamp", "TaxAnnualAmount", "TaxAssessedValue",
  "TaxLegalDescription", "TaxType", "TaxYear", "TimestampSQL", "Topography", "TransactionType", "TruckLevelShippingDoors",
  "TruckLevelShippingDoorsHeightFeet", "TruckLevelShippingDoorsHeightInches", "TruckLevelShippingDoorsWidthFeet",
  "TruckLevelShippingDoorsWidthInches", "UFFI", "UnderContract", "UnitNumber", "UnparsedAddress", "Utilities",
  "VacancyAllowance", "VendorPropertyInfoStatement", "View", "VirtualTourFlagYN", "VirtualTourURLBranded",
  "VirtualTourURLBranded2", "VirtualTourURLUnbranded", "VirtualTourURLUnbranded2", "WashroomsType1", "WashroomsType1Level",
  "WashroomsType1Pcs", "WashroomsType2", "WashroomsType2Level", "WashroomsType2Pcs", "WashroomsType3", "WashroomsType3Level",
  "WashroomsType3Pcs", "WashroomsType4", "WashroomsType4Level", "WashroomsType4Pcs", "WashroomsType5", "WashroomsType5Level",
  "WashroomsType5Pcs", "WaterBodyName", "WaterBodyType", "WaterDeliveryFeature", "WaterExpense", "WaterFrontageFt",
  "WaterFrontageUnits", "WaterSource", "WaterView", "Waterfront", "WaterfrontAccessory", "WaterfrontFeatures", "WaterfrontYN",
  "WellCapacity", "WellCapacityUnits", "WellDepth", "WellDepthUnits", "ZoningDesignation",
];
