/**
 * VOW Property resource: Standard Name list (all property fields per VOW schema).
 * Used in $select to request full VOW property data. ListingKey is added by the fetch.
 */
export const VOW_PROPERTY_FIELDS = [
  "AccessToProperty", "AccessibilityFeatures", "AddChangeTimestamp", "AdditionalMonthlyFee",
  "AdditionalMonthlyFeeFrequency", "AlternativePower", "Amps", "ApartmentNumber", "ApproximateAge",
  "ArchitecturalStyle", "AssessmentYear", "AssignmentYN", "AssociationAmenities", "AssociationFee",
  "AssociationFeeIncludes", "AssociationName", "AssociationYN", "AttachedGarageYN", "BackOnMarketEntryTimestamp",
  "BalconyType", "Basement", "BasementYN", "BathroomsTotalInteger", "BaySizeLengthFeet", "BaySizeLengthInches",
  "BaySizeWidthFeet", "BaySizeWidthInches", "BedroomsAboveGrade", "BedroomsBelowGrade", "BedroomsTotal",
  "BoardPropertyType", "BrokerFaxNumber", "BuildingAreaTotal", "BuildingAreaUnits", "BuildingName",
  "BusinessName", "BusinessType", "BuyOptionYN", "BuyerOfficeName", "CableYNA", "CarportSpaces",
  "CentralVacuumYN", "ChannelName", "ChattelsYN", "City", "CityRegion", "ClearHeightFeet", "ClearHeightInches",
  "CloseDate", "CloseDateHold", "ClosePrice", "ClosePriceHold", "CoBuyerOfficeName", "CoBuyerOfficeName3",
  "CoBuyerOfficeName4", "CoListAgentAOR", "CoListOfficeName", "CoListOfficeName3", "CoListOfficeName4",
  "CoListOfficePhone", "CommercialCondoFee", "CommercialCondoFeeFrequency", "CommonAreaUpcharge",
  "CommunityFeatures", "ConditionOfSale", "ConditionalExpiryDate", "CondoCorpNumber", "ConstructionMaterials",
  "ContactAfterExpiryYN", "ContractStatus", "Cooling", "CoolingYN", "Country", "CountyOrParish", "CoveredSpaces",
  "CraneYN", "CreditCheckYN", "CrossStreet", "DDFYN", "DaysOnMarket", "DealFellThroughEntryTimestamp",
  "DenFamilyroomYN", "DepositRequired", "DevelopmentChargesPaid", "DirectionFaces", "Directions",
  "DiscloseAfterClosingDate", "Disclosures", "DoNotDiscloseUntilClosingYN", "DockingType", "DoubleManShippingDoors",
  "DoubleManShippingDoorsHeightFeet", "DoubleManShippingDoorsHeightInches", "DoubleManShippingDoorsWidthFeet",
  "DoubleManShippingDoorsWidthInches", "DriveInLevelShippingDoors", "DriveInLevelShippingDoorsHeightFeet",
  "DriveInLevelShippingDoorsHeightInches", "DriveInLevelShippingDoorsWidthFeet", "DriveInLevelShippingDoorsWidthInches",
  "ElectricExpense", "ElectricOnPropertyYN", "ElectricYNA", "ElevatorType", "ElevatorYN", "EmploymentLetterYN",
  "EnergyCertificate", "EnsuiteLaundryYN", "EscapeClauseHours", "EscapeClauseYN", "EstimatedInventoryValueAtCost",
  "Exclusions", "ExerciseRoomGym", "Expenses", "ExpirationDate", "Exposure", "ExtensionEntryTimestamp",
  "ExteriorFeatures", "FarmFeatures", "FarmType", "FinancialStatementAvailableYN", "FireplaceFeatures",
  "FireplaceYN", "FireplacesTotal", "FoundationDetails", "FractionalOwnershipYN", "FranchiseYN", "FreestandingYN",
  "FrontageLength", "Furnished", "GarageParkingSpaces", "GarageType", "GarageYN", "GasYNA", "GradeLevelShippingDoors",
  "GradeLevelShippingDoorsHeightFeet", "GradeLevelShippingDoorsHeightInches", "GradeLevelShippingDoorsWidthFeet",
  "GradeLevelShippingDoorsWidthInches", "GreenCertificationLevel", "GreenPropertyInformationStatement", "GrossRevenue",
  "HSTApplication", "HandicappedEquippedYN", "HeatSource", "HeatSourceMulti", "HeatType", "HeatTypeMulti",
  "HeatingExpenses", "HeatingYN", "HoldoverDays", "HoursDaysOfOperation", "HoursDaysOfOperationDescription",
  "ImportTimestamp", "Inclusions", "IndustrialArea", "IndustrialAreaCode", "InsuranceExpense", "InteriorFeatures",
  "InternetAddressDisplayYN", "InternetEntireListingDisplayYN", "IslandYN", "KitchensAboveGrade", "KitchensBelowGrade",
  "KitchensTotal", "LaundryFeatures", "LaundryLevel", "LeaseAgreementYN", "LeaseAmount", "LeaseTerm",
  "LeaseToOwnEquipment", "LeasedConditionalEntryTimestamp", "LeasedEntryTimestamp", "LeasedLandFee", "LeasedTerms",
  "LegalApartmentNumber", "LegalStories", "LinkProperty", "LinkYN", "LiquorLicenseYN", "ListAOR", "ListOfficeName",
  "ListPrice", "ListPriceUnit", "ListingContractDate", "ListingId", "LivingAreaRange", "LocalImprovements",
  "LocalImprovementsComments", "Locker", "LockerLevel", "LockerNumber", "LockerUnit", "LotDepth", "LotDimensionsSource",
  "LotFeatures", "LotIrregularities", "LotShape", "LotSizeArea", "LotSizeAreaUnits", "LotSizeDimensions",
  "LotSizeRangeAcres", "LotSizeSource", "LotSizeUnits", "LotType", "LotWidth", "MLSAreaDistrictOldZone",
  "MLSAreaDistrictToronto", "MLSAreaMunicipalityDistrict", "MainLevelBathrooms", "MainLevelBedrooms", "MainOfficeKey",
  "MaintenanceExpense", "MajorChangeTimestamp", "MapColumn", "MapPage", "MapRow", "MaximumRentalMonthsTerm",
  "MediaChangeTimestamp", "MediaListingKey", "MinimumRentalTermMonths", "MlsStatus", "ModificationTimestamp",
  "MortgageComment", "NetOperatingIncome", "NewConstructionYN", "NumberOfFullTimeEmployees", "NumberOfKitchens",
  "NumberSharesPercent", "OccupantType", "OfficeApartmentArea", "OfficeApartmentAreaUnit", "OldPhotoInstructions",
  "OperatingExpense", "OriginalEntryTimestamp", "OriginalListPrice", "OriginalListPriceUnit", "OriginatingSystemID",
  "OriginatingSystemKey", "OriginatingSystemName", "OtherExpense", "OtherStructures", "OutOfAreaMunicipality",
  "OutsideStorageYN", "ParcelNumber", "ParcelNumber2", "ParcelOfTiedLand", "ParkingFeatures", "ParkingLevelUnit1",
  "ParkingLevelUnit2", "ParkingMonthlyCost", "ParkingSpaces", "ParkingSpot1", "ParkingSpot2", "ParkingTotal",
  "ParkingType1", "ParkingType2", "PaymentFrequency", "PaymentMethod", "PercentBuilding", "PercentListPrice",
  "PercentRent", "PermissionToContactListingBrokerToAdvertise", "PetsAllowed", "PhotosChangeTimestamp", "PictureYN",
  "PoolFeatures", "PortionLeaseComments", "PortionPropertyLease", "PossessionDate", "PossessionDetails",
  "PossessionType", "PostalCode", "PreviousListPrice", "PriceChangeTimestamp", "PriorMlsStatus", "PriorPriceCode",
  "PrivateEntranceYN", "PrivateRemarks", "ProfessionalManagementExpense", "PropertyAttachedYN", "PropertyFeatures",
  "PropertyManagementCompany", "PropertySubType", "PropertyType", "PropertyUse", "PublicRemarks", "PublicRemarksExtras",
  "PurchaseContractDate", "Rail", "RecreationRoomYN", "ReferencesRequiredYN", "RentIncludes", "RentalApplicationYN",
  "RentalItems", "RetailArea", "RetailAreaCode", "RoadAccessFee", "RollNumber", "Roof", "RoomsAboveGrade",
  "RoomsBelowGrade", "RoomsTotal", "RuralUtilities", "SalesBrochureUrl", "SaunaYN", "SeasonalDwelling", "SeatingCapacity",
  "SecurityFeatures", "SeniorCommunityYN", "Sewage", "Sewer", "SewerYNA", "Shoreline", "ShorelineAllowance",
  "ShorelineExposure", "ShorelineExposureMulti", "ShowingAppointments", "ShowingRequirements", "SignOnPropertyYN",
  "SoilTest", "SoilType", "SoldArea", "SoldAreaCode", "SoldAreaUnits", "SoldConditionalEntryTimestamp", "SoldEntryTimestamp",
  "SoundBiteUrl", "SourceSystemID", "SourceSystemName", "SpaYN", "SpecialDesignation", "SquareFootSource", "SquashRacquet",
  "StandardStatus", "StateOrProvince", "StatisCauseInternal", "StatusCertificateYN", "Status_aur", "StreetDirPrefix",
  "StreetDirSuffix", "StreetName", "StreetNumber", "StreetSuffix", "StreetSuffixCode", "StructureType", "SurveyAvailableYN",
  "SurveyType", "SuspendedDate", "SuspendedEntryTimestamp", "SystemModificationTimestamp", "TMI", "TaxAnnualAmount",
  "TaxAssessedValue", "TaxBookNumber", "TaxLegalDescription", "TaxType", "TaxYear", "TaxesExpense", "TelephoneYNA",
  "TerminatedDate", "TerminatedEntryTimestamp", "TimestampSQL", "Topography", "TotalExpenses", "Town",
  "TrailerParkingSpots", "TransactionBrokerCompensation", "TransactionType", "TruckLevelShippingDoors",
  "TruckLevelShippingDoorsHeightFeet", "TruckLevelShippingDoorsHeightInches", "TruckLevelShippingDoorsWidthFeet",
  "TruckLevelShippingDoorsWidthInches", "UFFI", "UnavailableDate", "UnderContract", "UnitNumber", "UnparsedAddress",
  "Utilities", "VacancyAllowance", "VendorPropertyInfoStatement", "View", "VirtualTourFlagYN", "VirtualTourURLBranded",
  "VirtualTourURLBranded2", "VirtualTourURLUnbranded", "VirtualTourURLUnbranded2", "Volts", "WashroomsType1",
  "WashroomsType1Level", "WashroomsType1Pcs", "WashroomsType2", "WashroomsType2Level", "WashroomsType2Pcs",
  "WashroomsType3", "WashroomsType3Level", "WashroomsType3Pcs", "WashroomsType4", "WashroomsType4Level", "WashroomsType4Pcs",
  "WashroomsType5", "WashroomsType5Level", "WashroomsType5Pcs", "Water", "WaterBodyName", "WaterBodyType",
  "WaterDeliveryFeature", "WaterExpense", "WaterFrontageFt", "WaterFrontageUnits", "WaterMeterYN", "WaterSource",
  "WaterView", "WaterYNA", "Waterfront", "WaterfrontAccessory", "WaterfrontFeatures", "WaterfrontYN", "WellCapacity",
  "WellCapacityUnits", "WellDepth", "WellDepthUnits", "Winterized", "Year1LeasePrice", "Year1LeasePriceHold",
  "Year2LeasePrice", "Year2LeasePriceHold", "Year3LeasePrice", "Year3LeasePriceHold", "Year4LeasePrice", "Year4LeasePriceHold",
  "Year5LeasePrice", "Year5LeasePriceHold", "YearExpenses", "Zoning", "ZoningDesignation",
];
