-- Superseded: agent data now lives only in public.agents.
-- Run sql/agents_table.sql once; it creates the table, RLS, trigger, and migrates from auth_agents_with_type if that table exists.
-- You do not need to run this file.
